<?php

namespace AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    /**takes in nothing
     * sorts the three most recent news articles
     * @Return $queryBuilder
     */
    public function lastThree() {
        $queryBuilder = $this->createQueryBuilder('news')
        ->orderBy('news.date', 'DESC')
        ->setMaxResults(3);

       return $queryBuilder->getQuery()->execute();
    }
}
